# Generated by Django 4.0.5 on 2022-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='full_desc',
        ),
        migrations.AddField(
            model_name='post',
            name='small_desc',
            field=models.TextField(default='This is Me'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
