# Generated by Django 4.0.5 on 2022-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_rename_body_post_full_desc_post_small_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
